### ISSUE TITLE
PKGI ALERT

### ISSUE THREAD

**Issue by avrel820** [bucanero/pkgi-ps3#103]
Hello i have downloaded PKGI from GitHub it is corrupted  the version on PS3 homebrew channel hat links back here is corrupted too .....On my PS3 running PKGI i get missing config.txt the filtering is missing too....
I have a working version of PKGI i got from elsewhere and it works just fine as intended ....
Just wanted to let you know about the error 
Regards :)

**Comment by bucanero** [comment]
The latest release works fine, there's no error at all. If you get an "integrity check error" when the app starts it's because you or someone else tried to modify the application files (EBOOT.BIN, ICON.PNG, etc).

If the app loads but you don't see any content, then it's an issue with the `config.txt` or `dbformat.txt` files. Check your setup to comply with the required format.

**Comment by avrel820** [comment]
what i do not understand both config.txt & dbformat.txt are missing
But i have downloaded PKGI linked by a Youtuber and installed it  It works fine no config.txt & dbformat.txt error 
why do i only get the problem when downloading it from github ??  surely i would have the same problem with every version if it was my ps3 the problem....

**Comment by bucanero** [comment]
The official release will never include any `config.txt` or `dbformat.txt` files, those should be added by the user and created from their own links.

I don't know about this Youtuber, but I assume they're just re-releasing my app with some text files. I don't support anyone who distributes my work with injected external files and I won't give any support for such unofficial versions.

**Comment by avrel820** [comment]
i have absolutely no idea how PKGI works so how to setup files or make them even less ...So that enplanes why when i first discovered PKGI why it was classed in video section on my ps3 and it had a much bigger database .... 
as i understand  you are the app maker and people add there own database ...no problem i know it's not up to you to support what other people do ....anyways thank you for taking time to answer me and enlightening me
