### ISSUE TITLE
Pkgi 1.2.2 boots me back to ps3 xmb

### ISSUE THREAD

**Issue by Marsh92** [bucanero/pkgi-ps3#110]
Hi I just downloaded the new version 1.2.2 straight from the pkgi app itself and now when I try to launch the app I get booted back out into the ps3s xmb Home Screen is there a fix to this?

**Comment by bucanero** [comment]
uninstall everything, install the official 1.2.2 release package and see if the app opens. Then if the app launches ok, upload your configuration files again and check if you get any errors.
