### ISSUE TITLE
PKGi Stopped Working

### ISSUE THREAD

**Issue by the-importer** [bucanero/pkgi-ps3#115]
I was queuing a bunch of games and PKGi stopped allowing my to do so. I figured I must have hit a some sort of limit, so I rebooted the system and let those queued files start their download. After the downloads and installations, I went back to PKGi, but now, my controller no longer respond, only thing I can do is quit the app.

My controller is indeed No. 1 and I've tried deleting and reinstalling the PKG for PKGi, same results. Anyone has any idea on what's happening here?

Cheers

UPDATE: Looks like deleting a PKG file doesn't delete the data. I used the Multiman dashboard to navigate through the file system, deleted everything regarding PKGi, reinstalled and now it works just fine.

**Comment by bucanero** [comment]
A mention about queue limits was posted on #74 , I think that nobody has provided any estimate or number of the limit of queued tasks, so for now the user should keep track of the stuff that has been loaded into the download manager.
