### ISSUE TITLE
increase PKGi database memory limit

### ISSUE THREAD

**Issue by KRWCLASSIC** [bucanero/pkgi-ps3#116]
When databases have total over approx. 25k pkg's in it it freezes, i tried to make big database for it and when i refresh pkgi it freezes on "refreshing... 8216 kb"

my db has something like 30k pkg's in it

when i delete for e.g. "pkgi_dlcs.txt" (biggest one) it normally loads and works so its too much things at once issue

**Comment by KRWCLASSIC** [comment]
if you want to see this database (or if i made it correctly) thats contents if my config.txt:

```
url_games https://raw.githubusercontent.com/KRWCLASSIC/PKGi-db/update-server/PS3_GAMES.tsv
url_dlcs https://raw.githubusercontent.com/KRWCLASSIC/PKGi-db/update-server/PS3_DLCS.tsv
url_themes https://raw.githubusercontent.com/KRWCLASSIC/PKGi-db/update-server/PS3_THEMES.tsv
url_avatars https://raw.githubusercontent.com/KRWCLASSIC/PKGi-db/update-server/PS3_AVATARS.tsv
url_demos https://raw.githubusercontent.com/KRWCLASSIC/PKGi-db/update-server/PS3_DEMOS.tsv
language en
content 0
sort name
order asc
filter EUR,USA
no_music 1

```

**Comment by bucanero** [comment]
there's a limit of 8 Mb (8388608 bytes) for all databases loaded in memory, so I assume that you went over that limit and the app failed.

**Comment by KRWCLASSIC** [comment]
> there's a limit of 8 Mb (8388608 bytes) for all databases loaded in memory, so I assume that you went over that limit and the app failed.
> 

yeah, there is chance u can increase this limit to 16mb?

**Comment by 1jtp8sobiu** [comment]
I agree with this, I use my customized DB that file size is more than 10MB and the app cant load it. Can you enhance the limit if possible?
