### ISSUE TITLE
(Background Mode) No funciona

### ISSUE THREAD

**Issue by Youngrpo** [bucanero/pkgi-ps3#12]
Hey bucanero, he probado a descargar con la opción Background mode y al hacer click en un juego no descarga en segundo plano, sino que se descarga desde alli entero 

Que puede ser?

**Comment by bucanero** [comment]
No es que se descargue el archivo, solamente se está creando un archivo "fantasma" para que luego el sistema de la PS3 pueda hacer la descarga en segundo plano. Debo mejorar los mensajes de la pantalla para evitar confusion con la descarga directa.

Una vez que se genera el archivo, ahi ya puedes salir de la aplicacion, y la proxima vez que inicies tu PS3 la descarga estará activa en segundo plano y descargando. (Puedes verlo en el XMB, Network -> Download Manager).

Por el momento es necesario reiniciar para que inicie la descarga en background.
