### ISSUE TITLE
Opcion de pausar musica

### ISSUE THREAD

**Issue by eze92** [bucanero/pkgi-ps3#13]
Buenas , podrias agregar en un futuro update la opcion de detener la musica de fondo , ya que por mas que deje de seleccionar la opcion sigue funcionando

**Comment by bucanero** [comment]
Solo es necesario desactivar la opción, guardar los settings y reiniciar la aplicación.
La musica no se ejecutará en el proximo inicio.

**Comment by bucanero** [comment]
Fixed in 323182d

Improvement will be available in next release.
