### ISSUE TITLE
Freezing PS3 error

### ISSUE THREAD

**Issue by guill3sm** [bucanero/pkgi-ps3#131]
White downloading ( both app directly or background ) console freezes after 1 or 2 minutes of downloading, adding details, this just happened now, before It was downloading pkg files with no issue ( using cobra cfw 4.90 ( phat PS3 console ))

**Comment by Masamune3210** [comment]
Cobra isn't even a CFW, it's just a component of them, and is in most if not all modern CFW's

**Comment by bucanero** [comment]
Background download tasks are managed by the ps3 firmware software, no code from pkgi is running there. 

The freeze is not only with direct downloads, that tells me that it has nothing to do with the pkgi app, but might be related to your ps3 system, your CFW or network interface.
