### ISSUE TITLE
constant clicking sound while in pkgi

### ISSUE THREAD

**Issue by classierdaisy65** [bucanero/pkgi-ps3#133]
as soon as I launch pkgi my ps3 starts outputting a weird click like sound that doesn't stop until pkgi is closed, does this every time the app is launched

console model: CECHK-01 (fat)
firmware: 4.90 evilnat cfw

https://github.com/bucanero/pkgi-ps3/assets/135450672/5d7bf7d3-6028-4ac3-b6c9-2333817eeec4

**Comment by bucanero** [comment]
nobody has ever reported such thing, so your system setup might have an issue. I suggest you try on another PS3.

you can also test disabling the background music from the settings menu (`triangle`).
