### ISSUE TITLE
ERROR Pkgi 1.2.4 on ps3 slim hen 3.2.2 (hfw 4.90)

### ISSUE THREAD

**Issue by alekslonewolf1992** [bucanero/pkgi-ps3#134]
Hi,
I want to report an issue.
Pkgi 1.2.4 doesn't seem to recognize the Config.txt & dbformat.txt  files. 

As always, i put the correct files in USDIR folder in hdd0/game/np00pkgi3/USDIR..

When i click on REFRESH, error remains and the library doesn't appear anymore.

I unistalled, then reinstalled, nothing. Issue remains. 

I haven't used the pkgi app for a long time.. Before it worked perfectly, at This moment not anymore. 

Can you do something? 

Thank you for everything

(photo in attachment)

![IMG_20230621_150922](https://github.com/bucanero/pkgi-ps3/assets/106822470/08da4897-77e1-4578-90e1-1f0bd8b7828a)

**Comment by fkoczan** [comment]
Hi, I use PKGI on PS3 Super Slim, same version, same HEN.....and it works....

**Comment by alekslonewolf1992** [comment]
Thank you 
Now it works again As usually
