### ISSUE TITLE
Icon not changing?

### ISSUE THREAD

**Issue by ElvisTekencio01** [bucanero/pkgi-ps3#136]
Well, i tried the app and the icon changed but i used a pkg on the net with the required .txt in the correct format. Installed again the app and used .txt files not a pkg and now the icon won't change, is the gray square not the black rectangle. Is it normal? I can use the app but the icon kinda bothers me.
Not sure if a issue, sry.

**Comment by bucanero** [comment]
The app icon changed in the latest version. If you want the old icon, you'll have to use any older version, like v1.2.2 .

**Comment by ElvisTekencio01** [comment]
Oh, ok thanks.
