### ISSUE TITLE
podrias hacer PKGI compatible con las bases de datos de esta web?

### ISSUE THREAD

**Issue by JLVegeta** [bucanero/pkgi-ps3#14]
buenas, ¿podrias hacer que PKGI fuese compatible con las bases de datos de esta web?

http://nopaystation.com

**Comment by bucanero** [comment]
Duplicate of #2

**Comment by bucanero** [comment]
La aplicación ya es compatible con cualquier base de datos. Solo es necesario crear un archivo `dbformat.txt` para definir correctamente el formato y columnas de los datos.

En esta seccion se detalla como crear y definir ese archivo:
https://github.com/bucanero/pkgi-ps3#user-defined-db-format
