### ISSUE TITLE
HFS Manifest handling 

### ISSUE THREAD

**Issue by Sumea** [bucanero/pkgi-ps3#144]
So, I found out something somewhat obscure, maybe because this seems to be more common on EUR versions of games than US/JPN ones (Thus far I seen two EUR examples)

Some data that PKGI can access seems to be split and manages by PS3 somehow, and given in .xml format hfs manifest. This manifest instead points to the file in multiple parts of usually under 5 gigabytes. These are also not like some downloadable games in multiple PKG's like Ni No Kuni or Uncharted 3, as these files need to be also joined which is something the PS3 manages as well, somehow when triggering the download officially. But end user dealing with these types of titles need to use good old copy /b in windows or equal tool of their choice.

I know these downloads are handled by PS3's downloader/Background downloader as I have downloaded such games officially on unmodified PS3.

**Comment by bucanero** [comment]
the issue with links with XML has been discussed #34 . A possible solution would be to generate a proper background download task with the information so the system can download the parts as needed.

But I have other projects so not sure if I'll take a look at some point.
