### ISSUE TITLE
No Configuration File.

### ISSUE THREAD

**Issue by NickDeBeenSAE** [bucanero/pkgi-ps3#149]
I'll let the title speak for itself as the downloaded file only contains pkgi.pkg

**Comment by bucanero** [comment]
Read the docs:
https://github.com/bucanero/pkgi-ps3?tab=readme-ov-file#setup-instructions

**Comment by NickDeBeenSAE** [comment]
No, I think you should add the config file, and you won't get hounded for it.

This really is a requirement of every application run on the PS3.

**Comment by bucanero** [comment]
**READ THE DOCS**, or don't use my homebrew apps.
