### ISSUE TITLE
Weird booting out sometimes

### ISSUE THREAD

**Issue by amazi69** [bucanero/pkgi-ps3#15]
I have no idea why this happens, But it always happens when I have downloaded multiple things it’s not major but annoying

**Comment by bucanero** [comment]
I don't understand what's the issue here... could you explain further?

**Comment by theozarkhippie78** [comment]
What he/she is saying is when u go to exit out of pkgi it kinda dose this freeze up thing but only if u add alot of background downloads I had the same issue but I'm happy that this works and I don't have to go through the process of downloading the game copying and installing I are a genius and I appreciate u ty so much for your time and consideration to us all that love the ps3 modding scene.

**Comment by bucanero** [comment]
thanks for your comments @theozarkhippie78  😄

**Comment by bucanero** [comment]
I wonder if you mean a kind of "screen flicker" that can happen when you want to Exit the app and the "Exit to XMB?" confirmation dialog show up ?
