### ISSUE TITLE
lastest pkgi no longer showing "missing raps" unless you press [] and check 

### ISSUE THREAD

**Issue by wankio** [bucanero/pkgi-ps3#150]
How to re-enabled it so i will no which game i need to skip, without [] to checking raps available or not

**Comment by bucanero** [comment]
The application has never included such feature. Also the app doesn't provide any links, it has to be added by the user.

You could filter your database files manually if needed.

**Comment by wankio** [comment]
it does "[image](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F4lfh9pmgo6x71.jpg%3Fauto%3Dwebp%26s%3D2eeb03e34e400c372736b4f0d17bd6ad32c9572b)" 
anyway, i just manual find all missing raps game and delete them all :)

**Comment by bucanero** [comment]
No , it does not, I know the code I wrote. What you're showing is a database file where someone edited titles and add a message about missing data. 

As stated, it's not the app doing anything.
