### ISSUE TITLE
Avatars and Themes not included?

### ISSUE THREAD

**Issue by gordonfuckingfreeman** [bucanero/pkgi-ps3#151]
Everything else is there. Games, DLC, some tools, that's fine. But the main reason why I downloaded PKGi were for the themes and avatars. Should I re-download and try again and again? I'm a little confused on what to do, considering this is the 3rd time that I had to download it.

**Comment by bucanero** [comment]
Any download links for content such as themes or avatars must be provided by the user. The official release will never include any kind of content.

You won't get support for any unofficial repacks or hacked versions.
