### ISSUE TITLE
Missing https support

### ISSUE THREAD

**Issue by XavierWrz** [bucanero/pkgi-ps3#19]
to get online databases working you know

**Comment by bucanero** [comment]
the app supports https already (since e239f6bf2a62d1670e5710fa37bf40c4ea147e08)
perhaps the issuing CA certs for the webserver are not supported, but that's a different topic

I'd suggest to use http URLs as a work-around.

**Comment by XavierWrz** [comment]
Thanks, changing to http did the job

**Comment by XavierWrz** [comment]
Also, is possible to filter content which has rap only in next versions?

**Comment by bucanero** [comment]
currently there's no filter for items without rap information. 
You'd have to do it offline, editing the database and removing the items there.
