### ISSUE TITLE
[Question] Is there planned support for ****Station.com?

### ISSUE THREAD

**Issue by duduke** [bucanero/pkgi-ps3#2]
http://****station.com/

**Comment by zecoxao** [comment]
tsv support would be great!

**Comment by bucanero** [comment]
> tsv support would be great!

I'm thinking about adding generic support for different type of text db files. (csv, tsv, semi-colon, etc.)

The basic idea for this feature, as I see it: you'd have to define the column separator delimiter (eg. a pipe "|"), and the order of the columns.

**Comment by s1cp** [comment]
I wrote a converter here https://gist.github.com/s1cp/ace6325154fac10c9211ac1cf3cfab85
In doing so, I discovered several bugs with the app itself which I'll try to open issues for.

**Comment by bucanero** [comment]
the generic "db format" feature is ready. I've been testing with many different formats, column orders, delimiters, et al.

I just need to write down an explanation on how to write a "dbformat.txt" config file to define any custom database.

**Comment by bucanero** [comment]
v1.0.5
