### ISSUE TITLE
Dlc's

### ISSUE THREAD

**Issue by razielsoulreaver** [bucanero/pkgi-ps3#21]
Would like to request Dlc Support for the app since many games have Dlc or many Dlc's and its a hazzle to download throughout the web page

**Comment by bucanero** [comment]
The latest version of the PKGi app already supports DLC's. Have you tried the v1.1.2?

**Comment by razielsoulreaver** [comment]
yeah sorry i did not know found a way to add the txt files for dlc's thank you!
