### ISSUE TITLE
This content can be used if you renew the licence in PlayStation Store

### ISSUE THREAD

**Issue by devoided** [bucanero/pkgi-ps3#22]
Any idea why I'm getting this when launching an installed game?

I'm using Jabu's NPS to PS3 to generate a TSV (with rap codes) which is read successfully by your tool (Link: https://www.psxhax.com/threads/pkgi-ps3-playstation-3-port-of-pkgi-tool-downloader-installer-by-bucanero.7210/)

But for some reason I keep getting the following error for any game I install:

**This content can be used if you renew the licence in PlayStation Store**

It's almost like the rap code isn't being applied? Any thoughts?

**Comment by devoided** [comment]
Btw, on COBRA 8.2 with enabled

**Comment by devoided** [comment]
Fixed by activating console

**Comment by XavierWrz** [comment]
yes, you need to activate console so cobra payload auto-activates the game with its .RAP
