### ISSUE TITLE
Categories not working with custom formatted txt files, odd behavior with large pkgi.txt files

### ISSUE THREAD

**Issue by bitrot-alpha** [bucanero/pkgi-ps3#25]
[bug report.zip](https://github.com/bucanero/pkgi-ps3/files/4259537/bug.report.zip)
[bug report 2.zip](https://github.com/bucanero/pkgi-ps3/files/4259552/bug.report.2.zip)
I tried formatting my files per the readme.md, and they loaded in the app, but the categories function isn't working properly, (at least for me). If I tag something with the type **1**/Game, it'll correctly show up in the games category (and tells me it's a game when I press **[ ]**), but my problem is that everything shows up in the game category *regardless* if it is tagged with the type **1** or any other type, which shows up as **Unknown** when I press Square/**[ ]**.

Also, I have issues when I try to use more than 3 `pkgi_*.txt` files and the app gets stuck at `'loading pkgi.txt'` and shows the database at **16384 games.** I am using the NoPayStation tsvs [http://nopaystation.com/](url) formatted with Excel to conform the the dbformat.txt that I have included in the zip. I think the problem may be that I hit the hard limit of items that can be in the database, as I have hit over 15000 items with the app actually running.

I'd be happy to do some testing on the app, but I can't compile from source due to my internet being slow.

My PS3 is a **CECHH01** running FERROX **4.85.1** CFW if that helps any.

Anyways, thanks for making such a great app already!

**Comment by bitrot-alpha** [comment]
Also, the tsv files from that website have a header line with column names, and if I leave that header in, the app doesn't like that either, and completely messes up the type flags. I understand that working that in would probably require quite a bit of work on the parser, so I leave this comment as a suggestion.

**Comment by bucanero** [comment]
most issues about the app getting stuck in the `loading pkgi.txt...` are related to improper databases or wrong dbformat.txt files... if any of those files don't perfectly match each other, the parser will get stuck there

I'd suggest to check this forum thread:
https://www.psx-place.com/threads/pkgi-ps3-v1-1-2-released.27354/

there's information and feedback from many users about settings, formats and general setup.
