### ISSUE TITLE
"Already installed" DLC's issue

### ISSUE THREAD

**Issue by GisTypical** [bucanero/pkgi-ps3#27]
I can install every other DLC, but if i have an installed and updated game, it shows that all the DLC's available for that game are installed when is not.

**Comment by bucanero** [comment]
yes, it's a known issue due to the simplified "item installed" function.

The issue has been addressed in https://github.com/bucanero/pkgi-ps3/commit/fa409e3c8a27fbcad45d1a2e1f5238c6ff70bfc1 

The fix should be included in the next release.

**Comment by bucanero** [comment]
Fixed in [v1.1.3](https://github.com/bucanero/pkgi-ps3/releases/tag/v1.1.3)
