### ISSUE TITLE
Already Installed Error when installing DLC

### ISSUE THREAD

**Issue by remlei** [bucanero/pkgi-ps3#28]
As title says,  install a DLC shows a Already Installed error.

how to trigger:
- Install a game data of any game and search for DLC on PKGi, it will result on Already Installed error
- It can also trigger by just installing the game update as well (if the game data install is optional and have an update)
- It can also trigger if the digital version of the game is already installed and you want to install a DLC for the same game.
- It can also trigger if there's a existing DLC is installed of the same game.
- For some reason, even just creating a empty folder with same gameid inside the game folder on dev_hdd0 of the DLC will also trigger the already installed issue.

*well the apps is false flagging it was already installed when in reality its not as long as it detects the same GAMEID

the only solution for me this now is deleting the game data for game disc or the game it self if its a digital version, which can be annoying.

**Comment by bucanero** [comment]
This issue was addressed in https://github.com/bucanero/pkgi-ps3/commit/fa409e3c8a27fbcad45d1a2e1f5238c6ff70bfc1
