### ISSUE TITLE
Program doesn't ignore commas inside quotes

### ISSUE THREAD

**Issue by s1cp** [bucanero/pkgi-ps3#3]
If you have a game name with commas, the program will treat the comma as the CSV delimiter, regardless if it´s in quotes, as seen at https://github.com/bucanero/pkgi-ps3/blob/961ec416aa045ccb07884fd6296cd8d4784721dc/source/pkgi_db.c#L197

**Comment by bucanero** [comment]
Yes, this limitation is noted on the README (setup instructions):
`Note: name and description cannot contain newlines or commas.`

**Comment by bucanero** [comment]
With the new generic db format support, you can use any kind of delimiter (comma, semi-colon, pipe, tab, etc.) 

Even if it's not really fixed, choosing for example `;` as delimiter will actually avoid the problem.
