### ISSUE TITLE
Cola para agregar a background

### ISSUE THREAD

**Issue by zombillano** [bucanero/pkgi-ps3#31]
Veo que hablas español, así que creo que nos entenderemos mejor así. Pensaba en si es posible agregar la funcionalidad de una cola (queue) para agregar los contenidos a descargar al background. Con esto quiero decir que si es posible que podamos seleccionar los elementos a descargar sin tener que esperar a que lo agregue de uno en uno al background, de tal forma que se puedan seleccionar N elementos y que posteriormente los agregue al background (y se tarde las horas que tenga que tardar).

Así podriamos seleccionar por decir algo, 10 elementos de una sola vez y después dejar a la consola trabajando

**Comment by bucanero** [comment]
Con la ultima version 1.1.6 la creacion de archivos para background download es casi instantanea, por lo que creo que ya no es necesario una funcion para generar una cola de trabajo.

Simplemente se elige todo lo que se quiere descargar en segundo plano, y listo. Luego reiniciar la ps3 y la cola queda activa en el XMB

**Comment by Juesto** [comment]
Creo que también algunos quieren bajar multiples cosas y que no se hagan burbujas después.

Ponerlo en segundo plano causa eso.
