### ISSUE TITLE
Creacion de archivos para utilizar refresh

### ISSUE THREAD

**Issue by eze92** [bucanero/pkgi-ps3#33]
Que tal , estaba viendo que una de las funcionalidades, es que se puede agregar un archivo para que refresque automaticamente los archivos , es posible agregar en los links desde el servidor de https://nopaystation.com/  ? que por lo menos para la vita de esa forma forma funciona

**Comment by bucanero** [comment]
Valid URLs can be used for DB update. You can check the documentation here: https://github.com/bucanero/pkgi-ps3#online-db-update
