### ISSUE TITLE
File.txt

### ISSUE THREAD

**Issue by bear2k666** [bucanero/pkgi-ps3#39]
Hi! I installed this new version but it does not show, do I need the txt? If I do, where can I find it?

**Comment by bear2k666** [comment]
Sorry I just found it. It went to the network tab.

**Comment by bucanero** [comment]
Yes, the app was moved to the `Network` tab. See the [Changelog](https://github.com/bucanero/pkgi-ps3/blob/master/CHANGELOG.md) for details about the changes on the new version.
