### ISSUE TITLE
Program freezes if there's an invalid URL

### ISSUE THREAD

**Issue by s1cp** [bucanero/pkgi-ps3#5]
Whenever there's something that can't be interpreted as an URL such as the "MISSING" value after converting dbs to pkgi-ps3, the program freezes, but can be exitted using the PS Button.

**Comment by bucanero** [comment]
it freezes when loading the .txt db with the invalid URL, or when you try to actually download that invalid URL?

**Comment by s1cp** [comment]
It freezes when I try downloading the invalid URL. I stumbled upon this bug accidentally, when I converted a tsv to the pkgi-ps3 format and it had rows with "MISSING" as the URL column.

**Comment by bucanero** [comment]
fixed in v1.0.5
