### ISSUE TITLE
PKGi not launching, only black screen

### ISSUE THREAD

**Issue by androidian5980** [bucanero/pkgi-ps3#57]
I installed pkgi on my HEN ps3 and it won't start up. I've tried cleaning the file system, but every time it just crashes to a black screen and I have to force power it off. Is there something I did wrong?

**Comment by Abdou4321** [comment]
You have to start-up HEN everytime u launch your PS3

**Comment by maxnrm** [comment]
same here, HEN is enabled

was downloading Demon Souls then it crashed or smthg, and now its only black screen, when I launch it

**Comment by bucanero** [comment]
delete the app, and remove all the settings and configs... then try a clean install and see if it starts up.

**Comment by Espionage724** [comment]
I'm seeing this issue as well with 4.88 HEN. Sometimes pkgi loads fine, and other times it hard-locks the PS3.

What exactly would make pkgi only work _sometimes_?

**Comment by LasseVa** [comment]
For me it depended on controller port. If controller is assigned to port 1 everything works. In any other port startup ends with crash.
