### ISSUE TITLE
even pkgi creating the .rap files when I try to open a game I downloaded for it, a warning appears saying that I need to renew the game license to be able to play it, how do I solve this?

### ISSUE THREAD

**Issue by mansoe** [bucanero/pkgi-ps3#59]

**Comment by bucanero** [comment]
`.rap` files are not licenses, games won't work without a license. Also, your PS3 must be activated.

**Comment by Masamune3210** [comment]
Wouldn't you just have to install the raps using reactpsn?

**Comment by draigon30** [comment]
pues tu  debes descargar y instalar la lisencias hay muchos tutoriales de youtube sobre las licensias

**Comment by draigon30** [comment]
https://github.com/TheWizWikii/WIKISTORE-PSN-EDITION/releases/download/1.0.3/15.280_Licencias.pkg

bro aqui esta le link de wizwiki hay vas a encontrar las 15mil licencias descargalas las pasas a una usb lo llevas al pley lo conectas vas a direcrorio estandar y las descargas y si no da vas a administracion de cuentas apretas hay y hay adentro te van a aparecer varias opciones y vas a sistem activation(activacion de sistema) apretas hay y te vana aparecer 2 opciones apretas en game(juego) y hay dos opciones tu el das en activation sistema (activacion de sistema) y listo.... tu activas el sistema para que se te activen las licencias y no te aparesca mas ese error

**Comment by mansoe** [comment]
Tanks bro, you help me so lot, i'm do not understand a lot about it :/

Em seg, 9 de nov de 2020 14:22, Damián Parrino <notifications@github.com>
escreveu:

**Comment by draigon30** [comment]
Well, you must download and activate the licenses, there are many
tutorials on YouTube, if you want me to explain it to you, write to my
email emanuelzapata380@gmail.com
