### ISSUE TITLE
Non-ASCII characters appear as garbage on screen

### ISSUE THREAD

**Issue by s1cp** [bucanero/pkgi-ps3#6]
Non-ASCII characters such as Japanese ones show up as random symbols on screen.

**Comment by bucanero** [comment]
Yes, it's a current limitation. The font only supports the basic 255 ASCII characters.

Possible improvement using TTF fonts:
https://github.com/Zarh/ManaGunZ/blob/master/MGZ/source/main.c#L2408

**Comment by bucanero** [comment]
Japanese and non-ASCII character support has been added

it will be available in the next version.

**Comment by bucanero** [comment]
Fixed in v1.1.0
