### ISSUE TITLE
Freezing and black screen when opening PKGi on PS3Hen 4.87

### ISSUE THREAD

**Issue by jmarcospl** [bucanero/pkgi-ps3#62]
When opening PGKi on PS3Hen 4.87 there is a general crash and a black screen, which can only be fixed with forced console shutdown. Any tips?

Thanks!

**Comment by bucanero** [comment]
which `pkgi` version are you using? I'd suggest deleting the whole PKGI app, and trying an older version, for example v1.1.2
install only the app, without any configuration or settings, and run it once, to see if the app opens or not.

a few other users are on 4.87 +HEN using pkgi with no issues... so it might be the setup... try unloading any other stuff, like webman mod, sman, etc... and running pkgi again

**Comment by jmarcospl** [comment]
I realized that the problem started when I installed the .pkg downloaded by PKGi, but it can be pure coincidence.

I removed PKGi v1.1.8 from my PS3Hen and installed it again, and the problem stopped for now. 

Currently I only use the Webman Mod, could this cause conflicts?

Thanks :)

**Comment by bucanero** [comment]
I never had issues running pkgi along webman mod, but I was mentioning that for troubleshooting

good to hear that a re-install solved the issue. 👍
