### ISSUE TITLE
Can Cyrillic fonts be added?

### ISSUE THREAD

**Issue by ErikPshat** [bucanero/pkgi-ps3#63]
Can I add Cyrillic fonts to display the menu in the program window?

**Comment by bucanero** [comment]
the menu text uses a standard ASCII 16x32 bitmap font, but you could change it for your own cyrillic font and then adjust the strings in the source code to match it

The bitmap font file is embedded in the YA2D library, so you'd have to edit and recompile the lib:
https://github.com/bucanero/ya2d_ps3/blob/master/libya2d/source/font-16x32.c

btw, you can create your own bitmap font with a tool such as [LCD image converter](https://www.riuson.com/lcd-image-converter/)

**Comment by ErikPshat** [comment]
Yes, thanks a lot!
Now everything is clear. Basically, the font can be drawn in a bit mask on the knee. But in the LCD image converter, I even saw a description of the program in Russian, and he has a page on GitHub.
Thank you for such a quick response!

**Comment by bucanero** [comment]
glad to hear! 😄 

I was checking, and actually you could load the new bitmap font from `pkgi-ps3` code and leave `ya2d` lib as is; something like
```c
AddFontFromBitmapArray((u8 *) data_font_cyrillic, (u8 *) texture_mem, 0, 255, 16, 32, 1, BIT7_FIRST_PIXEL);
```

but for simplicity, if you replace the `font-16x32.c` file with your own font it should work just fine

enjoy the holiday season over there, Moscow is lovely in winter! cheers
