### ISSUE TITLE
sha256.h: No such file or directory

### ISSUE THREAD

**Issue by luizfernandonb** [bucanero/pkgi-ps3#68]
I'm trying to compile PKGI but I can't, because the header file sha256.h that should be in polarssl doesn't exist

Error:

```
pkgi_db.c
rifrap.c
In file included from /mnt/e/Programacao/Repositorios/pkgi-ps3/source/pkgi_db.c:4:0:
/mnt/e/Programacao/Repositorios/pkgi-ps3/include/pkgi_sha256.h:5:10: fatal error: polarssl/sha256.h: No such file or directory
 #include <polarssl/sha256.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/usr/local/ps3dev/base_rules:68: pkgi_db.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:127: build] Error 2
```

I have already recompiled polarssl through `015-polarssl.sh` but this file never appears

Any solution?

**Comment by bucanero** [comment]
Use the updated polarSSL library from my fork:
https://github.com/bucanero/ps3libraries/blob/master/scripts/015-polarssl-1.3.9.sh

**Comment by luizfernandonb** [comment]
> Use the updated polarSSL library from my fork:
> https://github.com/bucanero/ps3libraries/blob/master/scripts/015-polarssl-1.3.9.sh
Worked, thank you
