### ISSUE TITLE
Socat don't receive messages

### ISSUE THREAD

**Issue by luizfernandonb** [bucanero/pkgi-ps3#69]
I already installed socat compiling directly from the source, 
and I also put the `DEBUGLOG=1` flag in the make command, and before starting pkgi through PS3Load I start socat using `socat udp4-recv: 30000, ip-add-membership = 239.255.0.100: 0.0.0.0 -`, however when starting pkgi I don't get anything on the console, I suspect it's Windows (because I'm using Ubuntu 20.04.2 for WSL 1), but honestly I don't know, any ideas?

The console looks like this:
![image](https://user-images.githubusercontent.com/42288418/111052550-83415a80-843a-11eb-8c78-7a1c6882563b.png)

**Comment by bucanero** [comment]
probably network settings, firewalls or the virtualization messing with UDP traffic

you can change the dbglogger library initialization to save a log to disk, then you could dump the logs to `/dev_hdd0/tmp/somefile.txt`
