### ISSUE TITLE
pkgi-ps3 can't create "exdata" directory.

### ISSUE THREAD

**Issue by s1cp** [bucanero/pkgi-ps3#7]
When installing a game with the rap included in the .txr. file, it shows up an error if the exdata directory doesn't exist, you have to manually create it for the raps to be saved properly.

**Comment by bucanero** [comment]
Yes, I assumed all CFW /HEN consoles had the `/dev_hdd0/exdata` folder already created, but it seems it depends on each case.

A check should be easily added in the next version.

**Comment by bucanero** [comment]
Fixed, v1.0.5
