### ISSUE TITLE
I downloaded a game. Where is it?

### ISSUE THREAD

**Issue by indeedwatson** [bucanero/pkgi-ps3#70]
I downloaded MGS4 sons of the patriots, the code that shows up in pkgi is `NPUB31633`. It finished downloading and it says I need to reboot to continue.

I reboot and nothing happens. The game is not in the list of games. I go look for the file via the file manager and cannot find it, it's not in `/dev_hdd0/tmp/pkgi` like the readme says, and sorting folders by date modified, it's not anywhere.

Yet they're still occupying space in the HDD (around 26gb). What do I do?

**Comment by bucanero** [comment]
if you're using background downloads, the download process is managed by the PS3. Check the XMB `Network` tab, there's a download manager option there. (see https://github.com/bucanero/pkgi-ps3/discussions/49)

**Comment by indeedwatson** [comment]
yeah thanks i found it eventually, but this really should be documented somewhere

**Comment by Masamune3210** [comment]
Its the manager that psn used officially to download games, so its documented plenty, just not in relation to this perhaps

**Comment by indeedwatson** [comment]
Well yeah, but this is not an official thing, there's no reason to assume a sideloaded app will use the official app; much like if you use F-Droid in your phone, it won't involve the Play Store at all.

In addition to that the UI of pkgi said that the *download* was finished, and to reboot to *install*. This clearly wasn't the case, because it was in the download section of the manager.

There's not many issues in this repo and 3 are about this same problem, so I wouldn't be surprised if it keeps coming up if users are not pointed to that official download section, at least in the readme. It's even more confusing because the readme does say something about uncomplete downloads, but it doesn't match this case, leading me to think there was something wrong.
