### ISSUE TITLE
pkgi just says "creating rif" and doesn't download anything.

### ISSUE THREAD

**Issue by ezxpro** [bucanero/pkgi-ps3#76]
That's it. after configuring it, I can see a full list of PSN titles, but when I select one of them and press X, it just says "creating rif" and exits after a split second, nothing else happens.

**Comment by bucanero** [comment]
Check your settings, if you're using "background download" mode, then any task will be queued and you need to reboot your PS3. 
Change the setting to "direct download" and your downloads should start inside the app.
