### ISSUE TITLE
8002AE04 error

### ISSUE THREAD

**Issue by Carlj21** [bucanero/pkgi-ps3#87]
Hi,
I have the 8002AE04 error when try to install pkg from xmb.
The pkg was downloaded from pkgi with background download
Ps3 cfw 4.88 cex cobra 8.3

Any suggest?

**Comment by cinnamonmatexfce** [comment]
> 
> note: you should find the task files in `/dev_hdd0/vsh/task`

Mine were in `/dev_hdd0/vsh/game_pkg/80000001/`:
```
EP0101-GAMENAME.pkg
ICON_FILE
d0.pdb
d1.pbd
```
