### ISSUE TITLE
Display error during download

### ISSUE THREAD

**Issue by brainli13** [bucanero/pkgi-ps3#99]
When a game file is canceled during downloading, and then restart the download again, the download percentage and remaining time are wrong after repeated several times.
**See the video in the link below for details**
[Recorded video](https://streamable.com/ztd6el)

**Comment by bucanero** [comment]
I see the video but I don't see a way to reproduce it.

I have started and resumed a download a few times without problems. Even different urls, using http or ftp links and it works as expected.
Maybe it's an issue from the web-server that hosts the file?
